config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tops#index"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'privacy_policy', to: 'tops#privacy_policy'
  get 'terms_of_service', to: 'tops#terms_of_service'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # post '/callback', to: 'linebot#callback'

  get 'senryus/ranking', to: 'senryus#ranking'

  resources :users, only: %i[new create]
  resources :senryus do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :favorites
      get 'ranking'
      get :user_senryus
    end
  end
  resources :favorites, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :senryu

  validates :content, presence: true, length: { maximum: 65_535 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.senryu }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@comment, partial: "comments/form", locals: { comment: @comment }),
                 status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @comment.senryu }
      format.turbo_stream
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(senryu_id: params[:senryu_id])
  end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <table class="border-separate" style="border-spacing: 0; width: 100%;">
    <tr id="comment-<%= comment.id %>" class="border-2 border-gray-600 bg-white hover:bg-gray-50" style="background-color: #f0f0f0;">
      <td class="py-4 px-6">
        <div class="flex items-center space-x-4">
          <%= image_tag comment.user.icon_url, alt: "user icon", class: "rounded-full w-10 h-10 shadow-sm" %>
          <h3 class="text-sm font-semibold text-gray-900"><%= comment.user.name %></h3>
        </div>
        <div id="js-comment-<%= comment.id %>" class="mt-2 whitespace-pre-wrap text-sm text-gray-700">
          <%= simple_format(comment.content) %>
        </div>
      </td>

      <% if current_user.own?(comment) %>
        <td class="py-4 px-6">
          <div class="flex justify-end">
            <%= link_to raw('<svg xmlns="http://www.w3.org/2000/svg" height="16" width="14" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>'), comment_path(comment), method: :delete, data: { turbo_confirm: t('defaults.message.delete_confirm'), turbo_method: :delete }, class: "inline-flex items-center p-1 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
          </div>
        </td>
      <% end %>
    </tr>
  </table>
<% end %>

app/views/comments/_comments.html.erb
<%= turbo_frame_tag "comments" do %>
  <% @comments.each do |comment| %>
    <%= render "comments/comment", comment: comment %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<div class="mx-auto mb-6 lg:w-2/3">
  <%= form_with model: comment, url: [senryu, comment], id: 'new_comment' do |f| %>
    <label for="content" class="block text-sm font-medium text-gray-700">
      <%= f.label :content %>
    </label>
    <%= f.text_area :content, class: 'form-control mb-3 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm', id: 'js-new-comment-body', rows: 4, placeholder: Comment.human_attribute_name(:content) %>
    <%= f.submit t('defaults.post'), class: 'inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500' %>
  <% end %>
</div>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend "comments", partial: "comments/comment", locals: { comment: @comment } %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove @comment %>