config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tops#index"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'privacy_policy', to: 'tops#privacy_policy'
  get 'terms_of_service', to: 'tops#terms_of_service'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # post '/callback', to: 'linebot#callback'

  get 'senryus/ranking', to: 'senryus#ranking'

  resources :users, only: %i[new create]
  resources :senryus do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :favorites
      get 'ranking'
      get :user_senryus
    end
  end
  resources :favorites, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
end

app/views/shared/_before_login_header.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ログイン前のナビゲーションバー</title>
<style>
  /* ドロップダウンメニュー内のリンクのスタイル */
  .menu-item {
    border-bottom: 1px solid #eee; /* 薄いグレーの区切り線 */
    margin: 5px 0; /* 上下のマージンでリンク間のスペースを開ける */
    padding: 10px 0; /* リンクの上下のパディングを増やす */
  }
  .menu-item:last-child {
    border-bottom: none; /* 最後のアイテムには区切り線を表示しない */
  }
  /* リンクにホバーした時の影 */
  .menu-item:hover {
    box-shadow: 0 2px 5px rgba(0,0,0,0.2); /* 影を追加 */
    transition: box-shadow 0.3s; /* スムーズな遷移 */
  }
</style>
</head>
<body>

<div class="navbar bg-base-100">
  <div class="flex-1">
  <%= link_to root_path, class: 'btn btn-ghost text-xl link' do %>
    <%= image_tag 'goshichide.png', class: "h-12", size: "70x70" %>
  <% end %>
  </div>
  <div class="flex-none">
    <div class="dropdown dropdown-end">
      <button tabindex="0" class="btn btn-square btn-ghost">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-5 h-5 stroke-current">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"></path>
        </svg>
      </button>
      <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
        <%= link_to t('senryus.index.title'), senryus_path, class: 'menu-item' %>
        <%= link_to (t 'defaults.login'), login_path, class: 'menu-item' %>
        <%= link_to t('users.new.title'), new_user_path, class: 'menu-item' %>
      </ul>
    </div>
  </div>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4" role="alert">
    <ul class="list-disc list-inside">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, message| %>
  <div class="<%= flash_class(key) %>" role="alert">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-10 bg-base-200 text-base-content rounded">
  <nav class="grid grid-flow-col gap-4">
    <%= link_to "利用規約", terms_of_service_path, class: "text-gray-500 transition duration-100 hover:underline active:text-indigo-600" %>
    <%= link_to "プライバシーポリシー", privacy_policy_path, class: "text-gray-500 transition duration-100 hover:underline active:text-indigo-600" %>
  </nav> 
  <aside>
    <p>Copyright ©2024_goshichide</p>
  </aside>
</footer>

app/views/shared/_header.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ナビゲーションバーのデモ</title>
<style>
  /* リンク間のスペースと区切り線のスタイル */
  .menu-item {
    border-bottom: 1px solid #eee; /* 薄いグレーの区切り線 */
    margin: 5px 0; /* 上下のマージンでリンク間のスペースを開ける */
    padding: 10px 0; /* リンクのパディングを調整 */
  }
  .menu-item:last-child {
    border-bottom: none; /* 最後のアイテムには区切り線を表示しない */
  }
  
  /* リンクにホバーした時の影 */
  .menu-item:hover {
    box-shadow: 0 2px 5px rgba(0,0,0,0.2);
    transition: box-shadow 0.3s ease-in-out;
  }

  .dropdown-content {
    z-index: 1000; /* 高い値を設定して前面に表示 */
  }
</style>
</head>
<body>

<div class="navbar bg-base-100">
  <div class="dropdown">
    <div tabindex="0" class="btn btn-square btn-ghost">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
      </svg>
    </div>
    <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
      <%= link_to t('senryus.new.title'), new_senryu_path, class: 'menu-item' %>
      <%= link_to t('senryus.index.title'), senryus_path, class: 'menu-item' %>
      <%= link_to t('senryus.favorites.title'), favorites_senryus_path, class: 'menu-item' %>
      <%= link_to t('senryus.ranking.title'), senryus_ranking_path, class: 'menu-item' %>
    </ul>
  </div>

  <div class="flex-1">
    <%= link_to root_path, class: 'btn btn-ghost text-xl link' do %>
      <%= image_tag 'goshichide.png', class: "h-12", size: "70x70" %>
    <% end %>
  </div>

  <!-- ユーザーアイコンのドロップダウンメニュー -->
  <div class="dropdown dropdown-end">
    <div tabindex="0" role="button" class="btn btn-ghost btn-circle icon">
      <div class="w-10 rounded-full">
        <%= image_tag(current_user.icon_url, alt: "user icon", class: "w-10 rounded-full") %>
      </div>
    </div>
    <ul tabindex="0" class="mt-3 z-[1] p-2 shadow menu menu-sm dropdown-content bg-base-100 rounded-box w-52">
      <%= link_to (t 'profiles.show.title'), profile_path, class: 'menu-item' %>
      <%= link_to (t 'senryus.user_senryus.title'), user_senryus_senryus_path, class: 'menu-item' %>
      <%= link_to (t 'defaults.logout'), logout_path, data: { turbo_method: :delete }, class: 'menu-item' %>
    </ul>
  </div>
</div>

</body>
</html>