config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tops#index"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'privacy_policy', to: 'tops#privacy_policy'
  get 'terms_of_service', to: 'tops#terms_of_service'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # post '/callback', to: 'linebot#callback'

  get 'senryus/ranking', to: 'senryus#ranking'

  resources :users, only: %i[new create]
  resources :senryus do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :favorites
      get 'ranking'
      get :user_senryus
    end
  end
  resources :favorites, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
end

app/models/senryu.rb
class Senryu < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :kamigo, presence: true, length: { maximum: 10 }
  validates :nakashichi, presence: true, length: { maximum: 10 }
  validates :shimogo, presence: true, length: { maximum: 10 }

  include PgSearch::Model
  pg_search_scope :search_by_all_parts,
                  against: %i[kamigo nakashichi shimogo],
                  using: {
                    tsearch: { prefix: true }
                  }

  # お気に入りの数に基づいて川柳をランキングするクラスメソッド
  def self.ranked_by_favorites
    all_senryus = where('favorites_count > 0').order(favorites_count: :desc)
    rank = 0
    ranked_senryus = all_senryus.chunk { |senryu| senryu.favorites_count }
                                .flat_map do |_favorites_count, senryus|
                                  rank += 1
                                  senryus.map { |senryu| [rank, senryu] }
                                end
    ranked_senryus.take_while { |rank, _senryu| rank <= 3 }
  end
end

app/controllers/senryus_controller.rb
class SenryusController < ApplicationController
  skip_before_action :require_login, only: %i[index]
  before_action :set_senryu, only: %i[edit update destroy]

  def index
    @senryus = if params[:search].present?
                 Senryu.includes(:user).search_by_all_parts(params[:search]).order(created_at: :desc)
               else
                 Senryu.includes(:user).order(created_at: :desc)
               end
  end

  def show
    @senryu = Senryu.find(params[:id])
    @comment = Comment.new
    @comments = @senryu.comments.includes(:user).order(created_at: :desc)
  end

  def new
    @senryu = Senryu.new
  end

  def edit; end

  def create
    @senryu = current_user.senryus.build(senryu_params)
    if @senryu.save
      redirect_to senryus_path, success: t('defaults.message.created', item: Senryu.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: Senryu.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @senryu.update(senryu_params)
      redirect_to @senryu, success: t('defaults.message.updated', item: Senryu.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: Senryu.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @senryu.destroy
      redirect_to senryus_path, success: t('defaults.message.deleted', item: Senryu.model_name.human),
                                status: :see_other
    else
      redirect_to @senryu, danger: t('defaults.message.not_deleted', item: Senryu.model_name.human), status: :see_other
    end
  end

  def favorites
    @favorite_senryus = current_user.favorite_senryus.includes(:user).order(created_at: :desc)
  end

  def ranking
    @ranked_senryus = Senryu.ranked_by_favorites
  end

  def user_senryus
    @user_senryus = current_user.senryus.includes(:user).order(created_at: :desc)
  end

  private

  def senryu_params
    params.require(:senryu).permit(:kamigo, :nakashichi, :shimogo)
  end

  def set_senryu
    @senryu = current_user.senryus.find(params[:id])
  end
end

app/views/senryus/_crud_menus.html.erb
<ul class='flex justify-end'>
  <li class="mr-2">
    <%= link_to edit_senryu_path(senryu), id: "button-edit-#{senryu.id}", class: "inline-block" do %>
      <svg xmlns="http://www.w3.org/2000/svg" height="16" width="16" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M441 58.9L453.1 71c9.4 9.4 9.4 24.6 0 33.9L424 134.1 377.9 88 407 58.9c9.4-9.4 24.6-9.4 33.9 0zM209.8 256.2L344 121.9 390.1 168 255.8 302.2c-2.9 2.9-6.5 5-10.4 6.1l-58.5 16.7 16.7-58.5c1.1-3.9 3.2-7.5 6.1-10.4zM373.1 25L175.8 222.2c-8.7 8.7-15 19.4-18.3 31.1l-28.6 100c-2.4 8.4-.1 17.4 6.1 23.6s15.2 8.5 23.6 6.1l100-28.6c11.8-3.4 22.5-9.7 31.1-18.3L487 138.9c28.1-28.1 28.1-73.7 0-101.8L474.9 25C446.8-3.1 401.2-3.1 373.1 25zM88 64C39.4 64 0 103.4 0 152V424c0 48.6 39.4 88 88 88H360c48.6 0 88-39.4 88-88V312c0-13.3-10.7-24-24-24s-24 10.7-24 24V424c0 22.1-17.9 40-40 40H88c-22.1 0-40-17.9-40-40V152c0-22.1 17.9-40 40-40H200c13.3 0 24-10.7 24-24s-10.7-24-24-24H88z"/></svg>
    <% end %>
  </li>
  <li>
    <%= link_to senryu_path(senryu), id: "button-delete-#{senryu.id}", data: { turbo_method: :delete, turbo_confirm: t('defaults.message.delete_confirm') }, class: "inline-block" do %>
      <svg xmlns="http://www.w3.org/2000/svg" height="16" width="14" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z"/></svg>
    <% end %>
  </li>
</ul>

app/views/senryus/_favorite.html.erb
<%= link_to favorites_path(senryu_id: senryu.id),
    id: "favorite-button-for-senryu-#{senryu.id}", 
    class:"float-right", 
    data: { turbo_method: :post } do %>
  <svg xmlns="http://www.w3.org/2000/svg" height="16" width="18" viewBox="0 0 576 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M287.9 0c9.2 0 17.6 5.2 21.6 13.5l68.6 141.3 153.2 22.6c9 1.3 16.5 7.6 19.3 16.3s.5 18.1-5.9 24.5L433.6 328.4l26.2 155.6c1.5 9-2.2 18.1-9.7 23.5s-17.3 6-25.3 1.7l-137-73.2L151 509.1c-8.1 4.3-17.9 3.7-25.3-1.7s-11.2-14.5-9.7-23.5l26.2-155.6L31.1 218.2c-6.5-6.4-8.7-15.9-5.9-24.5s10.3-14.9 19.3-16.3l153.2-22.6L266.3 13.5C270.4 5.2 278.7 0 287.9 0zm0 79L235.4 187.2c-3.5 7.1-10.2 12.1-18.1 13.3L99 217.9 184.9 303c5.5 5.5 8.1 13.3 6.8 21L171.4 443.7l105.2-56.2c7.1-3.8 15.6-3.8 22.6 0l105.2 56.2L384.2 324.1c-1.3-7.7 1.2-15.5 6.8-21l85.9-85.1L358.6 200.5c-7.8-1.2-14.6-6.1-18.1-13.3L287.9 79z"/></svg>
<% end %>

app/views/senryus/_favorite_button.html.erb
<% if current_user.favorite?(senryu) %>
  <%= render 'unfavorite', { senryu: senryu } %>
<% else %>
  <%= render 'favorite', { senryu: senryu } %>
<% end %>

app/views/senryus/_form.html.erb
<div class="flex justify-center items-center min-h-screen">
  <div class="card flex-shrink-0 w-full max-w-2xl shadow-2xl bg-base-100 border border-gray-400">
    <%= form_with model: senryu, local: true, html: {class: 'card-body'} do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-control">
        <%= f.label :kamigo %>
        <%= f.text_field :kamigo, class: "input input-bordered", placeholder: "5文字程度で入力してください" %>
      </div>
      <div class="form-control">
        <%= f.label :nakashichi %>
        <%= f.text_field :nakashichi, class: "input input-bordered", placeholder: "7文字程度で入力してください" %>
      </div>
      <div class="form-control">
        <%= f.label :shimogo %>
        <%= f.text_field :shimogo, class: "input input-bordered", placeholder: "5文字程度で入力してください" %>
      </div>
      <div class="form-control mt-6">
        <%= f.submit t('.submit'), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/senryus/_senryu.html.erb
<style>
  .gradient-border {
    position: relative;
    max-width: 520px;
    margin: 2em auto 2.5em;
    padding: 1.5em;
    border: 12px solid transparent;
    border-left-width: 48px;
    background: linear-gradient(#fff, #fff), linear-gradient(#b8c5db,#b8c5db);
    background-clip: padding-box, border-box;
    background-origin: border-box;
  }

  .gradient-border:before,
.gradient-border:after {
    display: inline-block;
    position: absolute;
    content: "";
}
.gradient-border:before {
    left: -36px;
    top: -32px;
    width: 24px;
    height: calc(100% + 64px);
    background: #4d4d4d;
}
.gradient-border:after {
    left: -48px;
    top: -20px;
    width: 48px;
    height: calc(100% + 40px);
    background: #4973b8;
}
</style>

<div class="w-full sm:w-3/4 md:w-2/3 lg:w-1/2 xl:w-1/3 px-4 mb-12">
  <div class="p-6 rounded-lg shadow-lg h-full gradient-border flex flex-col justify-between">
    <% [:kamigo, :nakashichi, :shimogo].each do |part| %>
      <p class="text-3xl font-semibold text-gray-900 mt-4">
        <%= link_to senryu.send(part), senryu_path(senryu) %>
      </p>
    <% end %>
    <div class="flex items-center justify-between mt-4">
      <div class="flex items-center">
        <%= image_tag senryu.user.icon_url, alt: "user icon", class: "rounded-full w-8 h-8 mr-2" %>
        <p class="text-right text-sm text-gray-500">
          <%= senryu.user.name %>
        </p>
      </div>
      <% if current_user %>
        <% if current_user.own?(senryu) %>
          <%= render 'crud_menus', senryu: senryu %>
        <% else %>
          <div class="ml-auto">
            <%= render 'favorite_button', senryu: senryu %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/senryus/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(senryu_id: senryu.id)), 
    id: "unfavorite-button-for-senryu-#{senryu.id}", 
    class:"float-right", 
    data: { turbo_method: :delete } do %>
  <svg xmlns="http://www.w3.org/2000/svg" height="16" width="18" viewBox="0 0 576 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M316.9 18C311.6 7 300.4 0 288.1 0s-23.4 7-28.8 18L195 150.3 51.4 171.5c-12 1.8-22 10.2-25.7 21.7s-.7 24.2 7.9 32.7L137.8 329 113.2 474.7c-2 12 3 24.2 12.9 31.3s23 8 33.8 2.3l128.3-68.5 128.3 68.5c10.8 5.7 23.9 4.9 33.8-2.3s14.9-19.3 12.9-31.3L438.5 329 542.7 225.9c8.6-8.5 11.7-21.2 7.9-32.7s-13.7-19.9-25.7-21.7L381.2 150.3 316.9 18z"/></svg>
<% end %>

app/views/senryus/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
  <div class="flex flex-wrap justify-center">
    <div class="w-full lg:w-2/3 px-4">
      <h1 class="text-xl font-bold leading-tight text-gray-900"><%= t('.title') %></h1>
      <%= render 'form', { senryu: @senryu } %>
    </div>
  </div>
</div>

app/views/senryus/favorites.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mx-auto pt-3">
  <div class="flex justify-center">
    <div class="w-full lg:w-10/12">
      <form class="flex">
        <input class="form-control flex-grow border border-r-0 rounded-l-lg py-2 px-4" placeholder="検索ワード" type="search" />
        <input type="submit" value="検索" class="btn bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-r-lg" />
      </form>
    </div>
  </div>

  <div class="mt-6">
    <div class="flex flex-wrap">
      <% if @favorite_senryus.present? %>
        <%= render @favorite_senryus %>
      <% else %>
        <p class="w-full text-center"><%= t('.no_result') %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/senryus/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mx-auto pt-3 px-4 lg:px-0">
  <div class="flex justify-center">
    <div class="w-full lg:w-10/12">
      <%= form_with(url: senryus_path, method: :get, local: true, html: { class: "flex" }) do |form| %>
        <%= form.text_field :search, class: "form-control flex-grow border border-r-0 rounded-l-lg py-2 px-4", placeholder: "検索ワード" %>
        <%= form.submit "検索", class: "btn bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-r-lg" %>
      <% end %>
    </div>
  </div>

  <div class="mt-6">
    <div class="flex flex-wrap -mx-4">
      <!-- 川柳の表示部分 -->
      <% if @senryus.present? %>
        <%= render partial: 'senryu', collection: @senryus, as: :senryu %>
      <% else %>
        <p class="w-full text-center"><%= t('.no_result') %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/senryus/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="mx-auto max-w-4xl">
  <div class="flex flex-wrap">
    <div class="w-full lg:w-8/12 lg:mx-auto">
      <h1 class="text-2xl font-bold"><%= t('.title') %></h1>
      <%= render 'form', { senryu: @senryu } %>
    </div>
  </div>
</div>

app/views/senryus/ranking.html.erb
<% content_for(:title, t('.title')) %>
<div class="senryu-container" style="display: flex; flex-direction: column; align-items: center; justify-content: center;">
  <% @ranked_senryus.each do |rank, senryu| %>
    <p class="text-lg font-semibold mb-2">
    <%= "第#{rank}位" %>: <%= senryu.favorites_count %> 
    </p>
    <%= render 'senryu', senryu: senryu, rank: rank %>
  <% end %>
</div>

app/views/senryus/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mx-auto pt-5">
    <div class="w-full lg:w-8/12 lg:mx-auto">
      <h1 class="text-2xl font-bold"><%= t('.title') %></h1>
      <article class="card bg-white shadow-xl">
          <div class='flex flex-wrap justify-center'>
              <%= render 'senryu', senryu: @senryu %>
              <div class="mt-4 text-right">
                <ul class="list-none">
                  <li class="inline"><%= l @senryu.created_at, format: :long  %></li>
                </ul>
              </div>
          </div>
      </article>
    </div>

  <%= render 'comments/form', { senryu: @senryu, comment: @comment } %>

  <%= render 'comments/comments', { comments: @comments } %>
</div>

app/views/senryus/user_senryus.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mx-auto pt-3">
  <div class="flex justify-center">
    <div class="w-full lg:w-10/12">
      <%= form_with(url: senryus_path, method: :get, local: true, html: { class: "flex" }) do |form| %>
        <%= form.text_field :search, class: "form-control flex-grow border border-r-0 rounded-l-lg py-2 px-4", placeholder: "検索ワード" %>
        <%= form.submit "検索", class: "btn bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-r-lg" %>
      <% end %>
    </div>
  </div>

  <div class="mt-6">
    <div class="flex flex-wrap">
      <!-- 川柳の表示部分 -->
      <% if @user_senryus.present? %>
        <%= render @user_senryus %>
      <% else %>
        <p class="w-full text-center"><%= t('.no_result') %></p>
      <% end %>
    </div>
  </div>
</div>