config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tops#index"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'privacy_policy', to: 'tops#privacy_policy'
  get 'terms_of_service', to: 'tops#terms_of_service'

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  # post '/callback', to: 'linebot#callback'

  get 'senryus/ranking', to: 'senryus#ranking'

  resources :users, only: %i[new create]
  resources :senryus do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get :favorites
      get 'ranking'
      get :user_senryus
    end
  end
  resources :favorites, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to senryus_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to login_path, status: :see_other, success: t('.success')
  end
end

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="bg-base-100">
  <!-- タイトルを中央揃えで配置 -->
  <div class="flex justify-center items-center pt-8">
    <h1 class="text-3xl font-bold mb-4"><%= t '.title' %></h1>
  </div>

  <div class="flex justify-center items-center min-h-screen">
    <!-- カードのレイアウトを調整 -->
    <div class="card flex-shrink-0 w-full max-w-2xl shadow-2xl bg-base-100 border border-gray-400">
      <%= form_with(url: login_path, local: true, html: { class: "card-body" }) do |f| %>
        <div class="form-control">
          <%= f.label :email, User.human_attribute_name(:email) %>
          <%= f.email_field :email, class: "input input-bordered", required: true %>
        </div>
        <div class="form-control">
          <%= f.label :password, User.human_attribute_name(:password) %>
          <%= f.password_field :password, class: "input input-bordered", required: true %>
        </div>
        <div class="form-control mt-6">
          <%= f.submit (t 'defaults.login'), class: "btn btn-primary" %>
        </div>
        <div class="form-control mt-4">
          <%= link_to 'LINEでログイン', auth_at_provider_path(provider: :line), class: "bg-blue-400 text-white p-2 rounded block text-center" %>
        </div>
        <div class="form-control mt-4">
          <label class="label">
            はじめての方はこちら
          </label>
          <%= link_to (t '.to_register_page'), new_user_path, class: "btn btn-primary mt-2" %>
        </div>
      <% end %>
    </div>
  </div>
</div>